apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["create", "get", "list", "update", "patch"]
