apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rolebinding
  namespace: delete
subjects:
- kind: ServiceAccount
  name: delete-sa
  namespace: delete
roleRef:
  kind: Role
  name: delete-role
  apiGroup: rbac.authorization.k8s.io

