apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-rolebinding
  namespace: view
subjects:
- kind: ServiceAccount
  name: view-sa
  namespace: view
roleRef:
  kind: Role
  name: view-role
  apiGroup: rbac.authorization.k8s.io

